INSERT INTO ENTITY_TEMPLATE(ID, NAME, OWNER) VALUES (99, 'Dennis Richie', 'user_test1');
INSERT INTO ENTITY_TEMPLATE(ID, NAME, OWNER) VALUES (100, 'Ada Lovelace', 'user_test1');
INSERT INTO ENTITY_TEMPLATE(ID, NAME, OWNER) VALUES (101, 'Linus Torvalds', 'user_test1');
INSERT INTO ENTITY_TEMPLATE(ID, NAME, OWNER) VALUES (102, 'José Valim', 'user_test2');